#ifndef TYPES_H
#define TYPES_H

// Piece type
enum PieceType {KING, QUEEN, ROOK, KNIGHT, BISHOP, PAWN};

// Color type
enum PieceColor {WHITE=1, BLACK=-1};

// Check status
enum BoardStatus {BS_NORMAL, BS_CHECKWHITE, BS_CHECKBLACK, BS_CHECKMATEWHITE, BS_CHECKMATEBLACK};

// Move type
enum MoveType {MT_NONE=0, MT_INVALID, MT_NORMAL, MT_CASTLING, MT_ENPASSANT, MT_PROMOTION_QUEEN, MT_PROMOTION_ROOK, MT_PROMOTION_KNIGHT, MT_PROMOTION_BISHOP};

#endif // TYPES_H

